
let datos = {
    'chat': [
      {
        id: 1,
        idcabecera: 28511,
        mensaje: 'Lorem ipsum dolor sit amet, lectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'facundo',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 2,
        idcabecera: 28511,
        mensaje: 'Lorem ipsum dolor sit amet,  quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'jose',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 3,
        idcabecera: 28511,
        mensaje: 'Lorem ipsum dolor sit amet, consecteturacere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'mapaez',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 4,
        idcabecera: 28511,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 5,
        idcabecera: 28511,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 6,
        idcabecera: 28511,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 7,
        idcabecera: 28511,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 8,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet, lectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'facundo',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 9,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet,  quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'jose',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 10,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet, consecteturacere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'mapaez',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 11,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 12,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 13,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 14,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 15,
        idcabecera: 28512,
        mensaje: 'Lorem ipsum dolor sit amet, lectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'facundo',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 16,
        idcabecera: 28513,
        mensaje: 'Lorem ipsum dolor sit amet,  quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'jose',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 17,
        idcabecera: 28513,
        mensaje: 'Lorem ipsum dolor sit amet, consecteturacere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'mapaez',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 18,
        idcabecera: 28513,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 19,
        idcabecera: 28513,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 20,
        idcabecera: 28514,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 21,
        idcabecera: 28514,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 22,
        idcabecera: 28514,
        mensaje: 'Lorem ipsum dolor sit amet, lectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'facundo',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 23,
        idcabecera: 28514,
        mensaje: 'Lorem ipsum dolor sit amet,  quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'jose',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 24,
        idcabecera: 28515,
        mensaje: 'Lorem ipsum dolor sit amet, consecteturacere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'mapaez',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 25,
        idcabecera: 28515,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 26,
        idcabecera: 28515,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },
      {
        id: 27,
        idcabecera: 28515,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"usuario",
        img:"https://bootdey.com/img/Content/avatar/avatar7.png"

      },
      {
        id: 28,
        idcabecera: 28515,
        mensaje: 'Lorem ipsum dolor sit amet, nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt officia quidem, architecto nulla doloribus excepturi delectus, maiores fugit doloremque sunt quis? Magnam labore nulla velit quo magni, facere eos voluptatibus.Lorem ipsum dolor sit amet, consectetur adipis',
        motivo: '1',
        usuario: 'embappe',
        ip: '172.20.254.205',
        fecha_mov: '2018-12-04 11:11:04.076532',
        leido: true,
        token_borrar:'6527',
        tipoorigen:'6527',
        fecha_leido:'2020-08-21 10:57:19.821493',
        usuario_leido:'false',
        privado:null,
        html:null,
        adjunto:null,
        interno:true,
        tipo_adjunto:null,
        idusuario:null,
        rol:"interno",
        img:"https://bootdey.com/img/Content/avatar/avatar6.png"

      },

      
    ]

  }
  
  module.exports.datos = datos;